# Generated by Django 4.0 on 2023-01-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=850)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('imglink', models.CharField(max_length=850)),
            ],
        ),
    ]
