# Generated by Django 4.0 on 2023-01-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
