# Generated by Django 4.0 on 2023-01-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_order_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_item', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=200)),
            ],
        ),
    ]
