# Generated by Django 4.0 on 2023-01-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=400)),
                ('payment_method', models.CharField(max_length=400)),
                ('payment_data', models.CharField(max_length=400)),
                ('fulfilled', models.BooleanField()),
                ('items', models.TextField()),
            ],
        ),
    ]
