# Generated by Django 4.0 on 2023-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_rename_first_name_order12_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order123',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
            ],
        ),
    ]
